# Build Spark Monitor with Maven
pool:
  # https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=vsts&tabs=yaml#use-a-microsoft-hosted-agent
  vmImage: 'ubuntu-16.04' # options: 'macOS-10.13', 'vs2017-win2016', 'ubuntu-16.04'

steps:
# Build with Apache Maven
- task: Maven@3
  inputs:
    mavenPomFile: '$(build.sourcesDirectory)/src/pom.xml' 
    jdkVersionOption: '1.8' # Optional. Options: default, 1.11, 1.10, 1.9, 1.8, 1.7, 1.6